sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1


  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t7Gz9zf2eGB4M7sfjuS
    access-key-secret: JF17U46VqTfgNCyXvJMoar9kkHnLFA
    bucket-name: web-tlias-itheima1
